In [ ]:
## 03 Numpy 索引及切片
内容：基本索引及切片 / 布尔型索引及切片

In [14]:
# 基本索引及切片
import numpy as np

ar = np.arange(20)
print(ar)
print(ar[4])
print(ar[3:6])   # 左闭又开
print('------')
# 一维数组索引及切片

ar = np.arange(16).reshape(4,4)
print(ar, '数组轴数为%i' %ar.ndim)
print(ar[2], '数组轴数为%i' %ar[2].ndim)
print(ar[2][1])
print(ar[1:3], '数组轴数为%i' %ar[1:3].ndim)
print(ar[2,2])
print(ar[:2,1:])
print('------')
# 二维数组索引及切片

ar = np.arange(8).reshape(2,2,2)
print(ar, '数组轴数为%i' %ar.ndim)
print(ar[0], '数组轴数为%i' %ar[0].ndim)
print(ar[0][0], '数组轴数为%i' %ar[0][0].ndim)
print(ar[0][0][1], '数组轴数为%i' %ar[0][0][1] .ndim)
# 三维数组索引及切片

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[3 4 5]
------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 数组轴数为2
[ 8  9 10 11] 数组轴数为1
9
[[ 4  5  6  7]
 [ 8  9 10 11]] 数组轴数为2
10
[[1 2 3]
 [5 6 7]]
------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 数组轴数为3
[[0 1]
 [2 3]] 数组轴数为2
[0 1] 数组轴数为1
1 数组轴数为0


In [9]:
# 布尔型索引及切片

ar = np.arange(12).reshape(3,4)
i = np.array([True, False, True])
j = np.array([True, True, False, False])
print(ar)
print(i)
print(j)
print(ar[i,:])
print(ar[:,j])

m = ar > 5
print(m)  # 这里m是一个判断矩阵
print(ar[m])  # 用m判断矩阵去筛选ar数组中大于5的元素！

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]
[ True  True False False]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [13]:
# 对数组索引及切片的值 做更改、复制

ar = np.arange(10)
print(ar)
ar[5] = 100
ar[7:9] = 200
print(ar)
# 索引切片后重新赋值，会更改原始数组

ar = np.arange(10)
a = ar.copy()
a[5] = 500
a[7:9] = 600
print(ar)
print(a)
# 养成 copy 的习惯，不更改原始数组

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 200 200   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 500   6 600 600   9]
