In [ ]:
## 02 Numpy 通用函数

# 数组形状：.T/.reshape()/.resize()
# 数组的复制  .copy()
# 数组类型转换：.astype()
# 数组堆叠  .hstack()/.vstack()
# 数组拆分： .hsplit()/.vsplit()
# 数组简单运算  .mean() .max() .min() .sum() .std() .var()

In [53]:
# 数组形状：.T/.reshape()/.resize()

ar1 = np.arange(10)
ar2 = np.ones((5,2))
print(ar1,'\n',ar1.T)
print(ar2,'\n',ar2.T)
print('------')

ar3 = ar1.reshape(2,5)   # 用法1：直接将已有数组改变形状
ar4 = np.zeros((4,6)).reshape(3,8)  # 用法2：生成数组后直接改变形状
ar5 = np.reshape(np.arange(12),(3,4))   # 用法3： 参数内添加（数组，目标形状）
print(ar1,'\n',ar3)
print(ar4)
print(ar5)
print('-------')
# .reshape 为数组提供新形状，而不更改其数据，所以元素数量需要一致。

ar6 = np.resize(np.arange(5),(3,4))
print(ar6)
# .resize 返回指定形状的新数组，如数量不一致，可以重复填充直至所需要数量的元素
# 注意：.T/.reshape/.resize 都是生成新的数组！

[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------
[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------
[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


In [57]:
# 数组的复制

ar1 = np.arange(10)
ar2 = ar1
print(ar2 is ar1)
ar1[2] = 9
print(ar1,ar2)
# ar1 和 ar2 指向同一个值，所以两者一起改变

ar3 = ar1.copy()
print(ar3 is ar1)  # ar3 是 ar1 的拷贝，不等于 ar1
ar1[0] = 9
print(ar1,ar3)

True
[0 1 9 3 4 5 6 7 8 9] [0 1 9 3 4 5 6 7 8 9]
False
[9 1 9 3 4 5 6 7 8 9] [0 1 9 3 4 5 6 7 8 9]


In [60]:
# 数组类型转换：.astype()

ar1 = np.arange(10,dtype=float)
print(ar1,ar1.dtype)

ar2 = ar1.astype(np.int32)   # 注意：养成好习惯，数组类型用 np.int32，而不是直接 int32
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int32


In [64]:
# 数组堆叠  .hstack/.vstack

a = np.arange(5)  
b = np.arange(5,9) 
ar1 = np.hstack((a,b))  # 注意：((a,b)) 这里形状可以不一样, 因为是一维数组
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
print('------')

a = np.array([[1],[2],[3]])  
b = np.array([['a'],['b'],['c']])  
ar2 = np.hstack((a,b))   # 注意：这里形状必须一样，否则无法堆叠
print(a,a.shape)
print(b,b.shape)
print(ar2,ar2.shape)
print('------')
# np.hstack(tup): 水平（按列顺序）堆叠数组


a = np.arange(5)  
b = np.arange(5,10)  
ar1 = np.vstack((a,b))  # 注意：((a,b)) 这里形状可以不一样, 因为是一维数组
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
print('------')
a = np.array([[1],[2],[3]])  # a为二维数组，3 行1 列
b = np.array([['a'],['b'],['c'],['d']])  # b 为二维数组，4 行1 列
ar2 = np.vstack((a,b))   # 注意：这里形状可以不一样，因为不影响垂直堆叠
print(a,a.shape)
print(b,b.shape)
print(ar2,ar2.shape)
print('------')
# np.vstack(tup): 垂直（按列顺序）堆叠数组

a = np.arange(5)  
b = np.arange(5,10)  
ar1 = np.stack((a,b)) 
ar2 = np.stack((a,b),axis=1)
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
print(ar2,ar2.shape)
# np.stack(array, axis=0): 沿着新轴连接数组的序列，形状必须一样！
# 重点解释 axis 参数的意思，假设两个数组[1 2 3]和[4 5 6], shape 均为(3,0)
# axis=0: [[1 2 3] [4 5 6]], shape为(2,3)
# axis=1: [[1 4] [2 5] [3 6]], shape为(3,2)

[0 1 2 3 4] (5,)
[5 6 7 8] (4,)
[0 1 2 3 4 5 6 7 8] (9,)
------
[[1]
 [2]
 [3]] (3, 1)
[['a']
 ['b']
 ['c']] (3, 1)
[['1' 'a']
 ['2' 'b']
 ['3' 'c']] (3, 2)
------
[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
------
[[1]
 [2]
 [3]] (3, 1)
[['a']
 ['b']
 ['c']
 ['d']] (4, 1)
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']
 ['d']] (7, 1)
------
[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] (5, 2)


In [67]:
# 数组拆分： .hsplit()/.vsplit()

ar = np.arange(16).reshape(4,4)
ar1 = np.hsplit(ar,2)
print(ar)
print(ar1,type(ar1))
# np.hsplit(ary, indices_or_sections): 将数组水平（按列）拆分为 n 个子数组
# 输出结果为列表，列表中元素为数组

ar2 = np.vsplit(ar,4)
print(ar2,type(ar2))
# np.vsplit(ary, indices_or_sections): 将数组垂直（按行）拆分为 n 个子数组
# 输出结果为列表，列表中元素为数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] <class 'list'>
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])] <class 'list'>


In [69]:
# 数组简单运算

ar = np.arange(6).reshape(2,3)
print(ar + 10)
print(ar * 2)
print(1 / (ar+1))
print(ar ** 0.5)

print(ar.mean())
print(ar.max())
print(ar.min())
print(ar.std())
print(ar.var())
print(ar.sum(), np.sum(ar,axis=0))  # np.sum()  axis=0 按列求和，axis=1 按行求和
print(np.sort(np.array([1,4,3,2,5,6])))  # 排序

[[10 11 12]
 [13 14 15]]
[[ 0  2  4]
 [ 6  8 10]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
2.5
5
0
1.707825127659933
2.9166666666666665
15 [3 5 7]
[1 2 3 4 5 6]
