In [ ]:
## 01 Numpy基础数据结构

NumPy数组是一个多维数组对象，称为ndarray。


In [6]:
# 多维数组 ndarray

import numpy as np

ar = np.array([1,2,3,4,5,6,7])
print(ar)          # 注意数组的格式：中括号，生成的数组元素之间没有逗号（和列表区分）
print(ar.ndim)     # 数组是几维的，或者说“秩”，维度的数量也称为 rank
print(ar.shape)    # 数组的形状，n 行 m 列的数组shape 为（n,m）
print(ar.size)     # 数组总共包含多少元素，对于 n行m列 的数组，元素个数为 n*m
print(ar.dtype)    # 数组中元素的类型，类似 type()(注意，type()是函数，.dtype是方法）
print(ar.itemsize) # 数组中每个元素的字节大小，int32的字节为 4，float64的字节为 8
print(ar.data)     # 包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要用这个属性
ar  # 交互方式下输出数组，会有 array(数组)，并且带有逗号

# 数组的基本属性
# 1.数组的维数成为秩（rank）, 一维数组的秩为 1，二维数组的秩为 2
# 2.在 Numpy 中，每一个线性的数组称为是一个轴（axes），秩其实是描述轴的数量

[1 2 3 4 5 6 7]
1
(7,)
7
int64
8


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
## 创建数组的常用方法
array() / arange() / linspace() / zeros()/zeros_like()/ones()/ones_like() / eye()

In [10]:
# 创建数组：array()函数，括号内可以是列表、元组、数组、生成器等

ar1 = np.array(range(10))  # 整型
ar2 = np.array([1,2,3.14,4,5])  # 浮点型
ar3 = np.array([[1,2,3],('a','b','c')])  # 二维数组：嵌套序列（列表、元组均可）
ar4 = np.array([[1,2,3],('a','b','c','d')])  # 注意：嵌套序列的数量不一样时，只能生成一维数组
print(ar1,type(ar1),ar1.dtype)
print(ar2,type(ar2),ar2.dtype)
print(ar3,ar3.shape,ar3.ndim,ar3.size)  # 二维数组，共有 6 个元素
print(ar4,ar4.shape,ar4.ndim,ar4.size)  # 一维数组，共有 2 个元素

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64
[1.   2.   3.14 4.   5.  ] <class 'numpy.ndarray'> float64
[['1' '2' '3']
 ['a' 'b' 'c']] (2, 3) 2 6
[list([1, 2, 3]) ('a', 'b', 'c', 'd')] (2,) 1 2


In [11]:
# 创建数组：arange()，类似 range(),在给定区间内返回均匀间隔的值

print(np.arange(10))   # 返回 0-9，整型
print(np.arange(10.0)) # 返回 0.0-9.0, 浮点型
print(np.arange(5,12)) # 返回 5-11
print(np.arange(5.0,12,2))  # 返回 5.0-12.0，间隔为 2
print(np.arange(10000)) # 如果数组太大而无法打印，Numpy会自动跳过数组的中心部分，只打印头尾

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11]
[ 5.  7.  9. 11.]
[   0    1    2 ... 9997 9998 9999]


In [17]:
# 创建数组：linspace(), 返回在区间[开始，停止]上计算的 num 个均匀间隔的样本，注意：两边均为闭区间

ar1 = np.linspace(2.0, 3.0, num=5)
ar2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
ar3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(ar1,type(ar1),ar1.dtype)
print(ar2)
print(ar3,type(ar3))
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# retstep: 如果为真，返回一个包含 2 个元素的元组：（数组，间隔长度）

[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'> float64
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


In [22]:
# 创建数组：zeros()/zeros_like()/ones()/ones_like()

ar1 = np.zeros(5)
ar2 = np.zeros((2,2), dtype = np.int)
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)
print('------')

ar3 = np.array([list(range(5)),list(range(5,10))])
ar4 = np.zeros_like(ar3)
print(ar3)
print(ar4)
print('------')
# zeros_like 返回具有与给定数组相同形状和类型的零数组

ar5 = np.ones(9)
ar6 = np.ones((2,3,4))  # 返回两个三行四列的数组
ar7 = np.ones_like(ar3)
print(ar5)
print(ar6)
print(ar7)

[0. 0. 0. 0. 0.] float64
[[0 0]
 [0 0]] int64
------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
# 创建数组：eye()

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
