In [ ]:
## Numpy 数据的输入和输出 

存储/读取数组数据、文本数据

In [3]:
# 存储数组数据  np.save()   文件类型为.npy

ar = np.random.rand(5,5)
print(ar)
np.save('arraytest.npy', ar)

[[0.16175186 0.74125214 0.42400165 0.99331158 0.87736178]
 [0.31774691 0.43518538 0.74224911 0.61382795 0.75633889]
 [0.04222206 0.93848983 0.14344606 0.22676804 0.34802574]
 [0.37025965 0.42755613 0.37374839 0.25724397 0.00963071]
 [0.06115985 0.14169514 0.53407195 0.85849326 0.52849053]]


In [4]:
# 读取数据  np.load()

ar_load = np.load('arraytest.npy')
print(ar_load)

[[0.16175186 0.74125214 0.42400165 0.99331158 0.87736178]
 [0.31774691 0.43518538 0.74224911 0.61382795 0.75633889]
 [0.04222206 0.93848983 0.14344606 0.22676804 0.34802574]
 [0.37025965 0.42755613 0.37374839 0.25724397 0.00963071]
 [0.06115985 0.14169514 0.53407195 0.85849326 0.52849053]]


In [12]:
# 存储、读取文本文件 np.savetxt() / np.loadtxt()

ar = np.random.rand(5,5)
np.savetxt('test.txt',ar, delimiter=',')  # 逗号分隔符
# numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

ar_loadtxt = np.loadtxt('test.txt', delimiter=',')
print(ar_loadtxt)

# numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)

[[0.64309762 0.22349004 0.79317466 0.48179888 0.61202061]
 [0.79487033 0.01305803 0.5492372  0.2064142  0.82125412]
 [0.32114516 0.99847423 0.09407061 0.7371685  0.30840132]
 [0.54442536 0.42065106 0.03519588 0.53881463 0.61522802]
 [0.30458482 0.83355311 0.3707986  0.69946859 0.54799468]]
